[package]
name    = "ibc-union-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
cosmwasm-schema       = { workspace = true }
cosmwasm-std          = { workspace = true }
cw-storage-plus       = { workspace = true }
ibc-union-msg         = { workspace = true }
macros.workspace      = true
schemars              = { workspace = true }
serde                 = { workspace = true }
serde-utils.workspace = true
thiserror.workspace   = true
unionlabs.workspace   = true
