[package]
description = "A small command line utility to ensure that blocks are produced on both sepolia and union."
name        = "ensure-blocks"
version     = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy              = { workspace = true, features = ["rpc", "rpc-types", "transports", "transport-http", "transport-ws", "reqwest", "provider-ws"] }
clap               = { workspace = true, features = ["default", "derive"] }
futures.workspace  = true
tendermint-rpc     = { workspace = true, features = ["http-client", "websocket-client"] }
tokio              = { workspace = true, features = ["full"] }
tracing-subscriber = { workspace = true }
