[package]
name    = "aptos-move-ibc"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
move-bindgen = { workspace = true }
tracing      = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
