[package]
name    = "ics008-wasm-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
cosmwasm-std             = { workspace = true }
frame-support-procedural = { workspace = true }
macros                   = { workspace = true }
prost                    = { workspace = true }
protos                   = { workspace = true, features = ["proto_full", "std"] }
serde                    = { workspace = true, features = ["derive"] }
serde-utils              = { workspace = true }
thiserror                = { workspace = true }
unionlabs                = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
