[package]
name    = "token-factory-api"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
cosmwasm-schema = { version = "1.5" }
cosmwasm-std    = { version = "1.5" }
